### ISSUE TITLE
url not working. 

### ISSUE THREAD

**Issue by Lokie-codes** [shashankkumar32/Pos-backend-jwt-auth#1]
the url included in the description is not working. Please get back to yourself and resolve the issue. If there was no error plesae document the proper way to connect

**Comment by shashankkumar32** [comment]
you have to create a user first from api/auth/register route using postman, then use auth/login to get the acess token then use that token as beareer in header to get the categories and items. Read me file will be uploaded after the front end completion , there is build error resolution going on docs will be there soon.

**Comment by shashankkumar32** [comment]
https://github.com/user-attachments/assets/cd71c330-8402-45cb-9646-c314d0dd592e

go through this video open routes and try creating post and get request based on that
